include: package:lint/analysis_options.yaml

linter:
  rules:
    prefer_single_quotes: true
    avoid_classes_with_only_static_members: false
    depend_on_referenced_packages: false

analyzer:
  exclude: 
    - '**/*.freezed.dart'
    - '**/*.g.dart'
    - lib/**/*.*.dart
    - lib/generated/*
  errors:
    missing_return: error