name: castit
networks:
  app_network:
    driver: bridge
services:
  server:
    image: ${DOCKER_REGISTRY-}castitserver
    build:
      context: .
      dockerfile: CastIt.Server/Dockerfile
    ports:
      - "9696:8080"
      - "9697:8081"
    networks:
      - app_network
    environment:
      CASTIT_SERVER_URL: $CASTIT_SERVER_URL