name: castit
description: Remote control app

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.1+16

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  cached_network_image: ^3.2.1
  device_info_plus: ^4.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.1.0
  get_it: ^7.2.0
  json_annotation: ^4.5.0
  logger: ^1.1.0
  network_info_plus: ^2.1.4+1
  nil: ^1.1.1
  package_info_plus: ^1.4.3+1
  path: ^1.8.1
  path_provider: ^2.0.11
  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.0.15
  signalr_core: ^1.1.1
  sprintf: ^6.0.2
  tuple: ^2.0.0
  url_launcher: ^6.1.5
  web_socket_channel: ^2.2.0

dev_dependencies:
  build_runner:
  freezed: ^2.1.0+1
  icons_launcher: ^2.0.5
  json_serializable: ^6.2.0
  lint: ^1.8.2

dependency_overrides:
  path: ^1.8.1

icons_launcher:
  image_path: "assets/icon/icon.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
    macos:
      enable: true

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png

flutter_intl:
  enabled: true
